version: '3'
services:
  server:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
  tsc:
    build: .
    volumes:
      - .:/usr/src/app
    command: "npm run tsc:watch"
