service: fmt

package:
  exclude:
    - mocks/**
    - src/**
    - dist/**/spec.ts
    - tsconfig.json

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  profile: fmt
  runtime: nodejs8.10
  region: eu-west-2
  environment:
    FMT_SITE_URL: https://fmt.surge.sh
    FMT_SUCCESS_LANDING_PAGE: https://fmt.surge.sh/success/
    SLACK_CLIENT_ID: ${file(.env.yml):SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${file(.env.yml):SLACK_SECRET}
    SLACK_OAUTH_ACCESS_URL: https://slack.com/api/oauth.access
    SLACK_OAUTH_AUTHORISATION_PAGE: https://slack.com/oauth/authorize
    SERVICE_ENDPOINT: https://jaknaccns7.execute-api.eu-west-2.amazonaws.com/dev

functions:
  slashCommand:
    handler: handler.slashCommand
    events:
      - http: POST slash-command

  authorise:
    handler: handler.authorise
    events:
      - http: GET oauth/authorise

  directInstall:
    handler: handler.directInstall
    events:
      - http: GET oauth/direct-install
