service: fmt

custom: ${file(slack-config.${opt:stage, 'dev'}.yml)}

package:
  exclude:
    - mocks/**
    - src/**
    - dist/**/spec.ts
    - tsconfig.json

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  profile: fmt
  runtime: nodejs8.10
  region: eu-west-2
  environment:
    FMT_SITE_URL: https://fmt.surge.sh
    FMT_SUCCESS_LANDING_PAGE: https://fmt.surge.sh/success/
    SLACK_OAUTH_ACCESS_URL: https://slack.com/api/oauth.access
    SLACK_OAUTH_AUTHORISATION_PAGE: https://slack.com/oauth/authorize
    SLACK_CLIENT_ID: ${self:custom.SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${self:custom.SLACK_SECRET}

functions:
  slashCommand:
    handler: handler.slashCommand
    events:
      - http: POST slash-command

  authorise:
    handler: handler.authorise
    events:
      - http: GET oauth/authorise

  directInstall:
    handler: handler.directInstall
    events:
      - http: GET oauth/direct-install
